version: '3.7'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/pos_db
      - STRIPE_SECRET_KEY=your-stripe-secret-key
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
